//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using VD.Data.Entity.MF;

namespace VD.Data.Entity
{
    public class User : BaseEntity
    {
        public User()
        {
          
        }
        [Display(Name = "Họ và tên")]
        public string Fullname { get; set; }

        [Display(Name = "Tài khoản")]
        public string Username { get; set; }
        [Display(Name = "Email")]
        public string Email { get; set; }
        [Display(Name = "Mật khẩu")]
        public string Password { get; set; }
        [Display(Name = "Số điện thoại")]
        public string Phone { get; set; }

        [Display(Name = "Hình ảnh")]
        public string Image { get; set; }

        [Display(Name = "Giới tính")]
        public string GioiTinh { get; set; }

        [Display(Name = "Địa chỉ")]
        public string Address { get; set; }

        //---role---
        [Display(Name = "Quyền hạn")]
        public int RoleId { get; set; }
        [ForeignKey("RoleId")]
        public virtual Role Role { get; set; }

        //---status---
        //1:kích hoạt
        [Display(Name = "Trạng thái")]
        public int UserStatusId { get; set; }
        [ForeignKey("UserStatusId")]
        public virtual UserStatus UserStatus { get; set; }

        //chủ
        public int? OwnerId { get; set; }
        [ForeignKey("OwnerId")]
        public virtual User Owner { get; set; }

        //member
        public virtual ICollection<User> Members { get; set; }

        //many to many
        public virtual ICollection<UserQuan> UserQuans { get; set; }

        //quan
        public virtual ICollection<Quan> Quans { get; set; }

        //Quán mặc định
        [Display(Name = "Quán mặc định")]
        public int? QuanDefaultId { get; set; }
        public static User[] seed()
        {
            int genid = 0;
            return new User[]
            {
                new User()
                {
                    Id = ++genid,
                    RoleId = 1,
                    UserStatusId = 1,
                    Username = "admin",
                    Password = "104255020101247154213024095114123176100126129011",
                 
                 
                    Phone = "123456798",
                    Address = "Sai gon",
                    Fullname = ""

                 
                },
                new User()
                {
                    Id = ++genid,
                    RoleId = 2,
                    UserStatusId =1, //hoat dong
                    Username = "123456789",
                    Password = "104255020101247154213024095114123176100126129011",
               
                
                    Phone = "123456798",
                    Address = "Sai gon",
                    Fullname = "Trần Gia Trang",
                },
            };
        }
    }
}
